### ISSUE TITLE
创建了自定义验证规则，使用时报错了

### ISSUE THREAD

**Issue by hesunfly** [hyperf/validation#12]
"hyperf/validation": "v2.1.10",

![image](https://user-images.githubusercontent.com/33787409/121038915-3b389680-c7e3-11eb-82bd-cc1265b15b6d.png)

![image](https://user-images.githubusercontent.com/33787409/121038931-3e338700-c7e3-11eb-82a4-c7a00e39b203.png)

![image](https://user-images.githubusercontent.com/33787409/121038957-425fa480-c7e3-11eb-9db8-549d7a2c9586.png)

不知道问题出来哪里了

**Comment by limingxinleo** [comment]
好好看文档

**Comment by hesunfly** [comment]
![image](https://user-images.githubusercontent.com/33787409/121042790-97e98080-c7e6-11eb-804f-18018fed6f7f.png)
不好意思，没看出来有什么不一样的，劳烦您指导一下了，谢谢😁

**Comment by CbYip** [comment]
是用手动创建验证器方式吧？需要在生成validator对象前重新进行一次extend的自定义规则。

**Comment by limingxinleo** [comment]
配置了没？

**Comment by hesunfly** [comment]
@limingxinleo  忘记配置事件监听了￣□￣｜｜，不好意思，犯了低级错误，刚开始用这个没多久，感谢提醒，现在可以正常使用了🌹
