### ISSUE TITLE
定义验证规则，响应message受限

### ISSUE THREAD

**Issue by MonkWang** [hyperf/validation#15]
定义一个 类似in：1，2 这样的规则，参数message无法灵活的定义 "字符长度必须要在 $min 至 $max 之间" 返回值

        $validatorFactory->extend('length', function ($attribute, $value, $parameters, $validator) use(&$lengthMsg) {
            $length = strlen($value);
            $count = count($parameters);
            if($count > 0){
                $min = $parameters[0];
                $max = $parameters[1];
                if($length > $max || $length < $min){
                    $lengthMsg = "字符长度必须要在 $min 至 $max 之间";
                    return false;
                }
                return true;
            }
            return true;
        }, $lengthMsg);

**Comment by huangzhhui** [comment]
所以这是一个功能建议吗？如果是，你应该直接提交一个 PR 而不是一个 issue
