### ISSUE TITLE
验证文件大小无效

### ISSUE THREAD

**Issue by hectorqin** [hyperf/validation#5]
```php
            $validator = $this->validationFactory->make(
                ['image' => $file],
                [
                    'image' => ['required', 'image', 'lte:10485760'],
                ]
            );

            if ($validator->fails()){
                throw new ValidationException($validator);
            }
```
我用上面的代码无法校验文件大小。

经调试发现，validateLte方法中 $value  是 Hyperf\HttpMessage\Upload\UploadedFile，不是numeric。无法进入文件大小的判断逻辑

https://github.com/hyperf/validation/blob/b32bae174711ea72e0eef8701a1e78f08fe0cea9/src/Concerns/ValidatesAttributes.php#L594

**Comment by huangzhhui** [comment]
Duplicate with https://github.com/hyperf/hyperf/issues/1329
